services:
  - type: web
    name: ateneo-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false  
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MERCADO_PAGO_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
    plan: free
